language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules

script:
  - npm run build
  - cp CNAME dist/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  keep_history: true
  on:
    branch: master