<template>
  <div class="text-page import">
    <h1>
      Custom playlists
    </h1>

    <v-alert
      class="notice"
      color="accent"
      dark
      v-if="parsedPlaylistId && parsedPlaylistId.startsWith('RD')"
    >
      This playlists starts with <b>"RD..."</b>, which could mean it's an
      autogenerated playlist and might not be imported properly or only
      import first 50 items correctly.
    </v-alert>

    <v-alert
      class="notice"
      color="accent"
      dark
      v-if="`bomb/${parsedPlaylistId}` in $store.state.customWords"
    >
      A playlist with this id was already imported.
      If you import it again it will overwrite old values.
    </v-alert>

    <v-alert
      class="notice"
      color="secondary"
      v-if="fetchError"
      dark
    >
      An error occured while loading playlist. Make sure
      <ul>
        <li> You are connected to internet. </li>
        <li> This playlist exists. </li>
        <li> This playlist is not set to private. </li>
      </ul>
      {{ fetchError }}
    </v-alert>

    <v-expansion-panels accordion v-model="openedPlaylist">
      <v-expansion-panel class="">
        <v-expansion-panel-header color="accent">
        <span style="color: white"> Import new playlist </span>
        </v-expansion-panel-header>

        <v-expansion-panel-content>
          <v-text-field
            label="YouTube Playlist"
            v-model="playlistLinkOrId"
            placeholder="Paste here"
            hint="Paste your YouTube or YouTube Music playlist link or id here."
          ></v-text-field>
          <v-btn
            color="primary"
            @click="savePlaylist();"
            :disabled="parsedPlaylistId === null"
          >
            Import YouTube Playlist
          </v-btn>
        </v-expansion-panel-content>
      </v-expansion-panel>

      <Playlist
        v-for="(playlist, index) in playlists"
        :key="playlist.id"
        v-model="playlists[index]"
        @delete="deletePlaylist(index)"
      />
    </v-expansion-panels>
    <HomeFab/>
  </div>
</template>

<style lang="scss">
@import "@/styles/_settings.scss";
.v-list, input {
  font-family: 'Epilogue', sans-serif;
}
.v-card__actions {
  .v-text-field {
    margin-top: 0;
    padding-top: 0;
  }
}
.import {
  .song-results, .notice {
    margin-top: 2em;
  }
  .v-messages {
    min-height: 16px;
    .v-messages__message {
      line-height: 14px;
    }
  }
  .alt-song-label {
    display: flex;
    flex: 1;
  }
}
</style>

<script lang="ts">
import Vue from 'vue';
import allWords from '@/lib/wordlists';
import PlaylistClass from '@/lib/playlist';
import HomeFab from '@/components/HomeFab.vue';
import Playlist from '@/components/Playlist.vue';

export default Vue.extend({
  name: 'Import',
  components: {
    HomeFab,
    Playlist,
  },
  data() {
    return {
      playlistLinkOrId: '',
      search: '',
      fetchError: '',
      playlists: [] as PlaylistClass[],
      playlistIdToIndex: {} as { [id: string]: number },
      openedPlaylist: 0,
    };
  },
  computed: {
    parsedPlaylistId(): string | null {
      return PlaylistClass.parseId(this.playlistLinkOrId);
    },
  },
  created() {
    this.playlists = Object.values(this.$store.state.customWords)
      .filter((list: any) => list.key.startsWith('bomb/'))
      .map(
        (list, index) => {
          const { key, name, items } = list as { key: string; name: string; items: string[] };
          const newPlaylist = new PlaylistClass(key.slice(5));
          newPlaylist.name = name;
          newPlaylist.songs = items.map(
            (s, id) => {
              const [author, title] = s.split(';', 2);
              return {
                id,
                author,
                title,
                alts: [
                  { author, title, confidence: 100 },
                  { author: title, title: author, confidence: 0 },
                ],
              };
            },
          );
          this.playlistIdToIndex[newPlaylist.id] = index;
          return newPlaylist;
        },
      );
  },
  watch: {
    playlists: {
      handler() {
        this.playlists.forEach((playlist) => {
          this.$store.commit('insertCustomWordlist', playlist.toJSON());
        });
      },
      deep: true,
    },
  },
  methods: {
    deletePlaylist(index: number) {
      const { key } = this.playlists[index].toJSON();
      this.playlists.splice(index, 1);
      this.playlistIdToIndex = {};
      this.openedPlaylist = -1;
      this.playlists.forEach(({ id }, idx) => {
        this.playlistIdToIndex[id] = idx;
      });
      this.$store.commit('removeCustomWordlist', key);
    },
    savePlaylist() {
      if (this.parsedPlaylistId === null) {
        return;
      }
      this.fetchError = '';
      const newPlaylist = new PlaylistClass(this.parsedPlaylistId);
      newPlaylist.fetch().then((playlist) => {
        this.playlistLinkOrId = '';
        if (newPlaylist.id in this.playlistIdToIndex) {
          const index = this.playlistIdToIndex[newPlaylist.id];
          this.playlists[index] = newPlaylist;
          this.openedPlaylist = index + 1;
        } else {
          this.playlistIdToIndex[newPlaylist.id] = this.playlists.length;
          this.playlists.push(newPlaylist);
          this.openedPlaylist = this.playlists.length;
        }
        const result = playlist.toJSON();
        if (result.key in this.$store.state.customWords) {
          const tree = allWords.findSubtree(result.key);
          tree.numWords -= tree.wordList.length;
          tree.wordList = [];
        }
        allWords.insertNode(result.key, result.items).name = result.name;
        this.$store.commit('insertSelectedWordlists', `/root/${result.key}`);
      }).catch((err) => { this.fetchError = err.toString(); });
    },
  },
});
</script>
